<?php

namespace WCS\FlyAroundBundle\Repository;

/**
 * PlaneModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaneModelRepository extends \Doctrine\ORM\EntityRepository
{
}
